.PHONY : clean
clean :
	-rm -f *.cpp *.h *~ *.bin
	-cd ./cfiles && rm -f *.cpp *.hpp *.o
	-cd ./binfiles && rm -f *.bin *.bin.*
	-cd ./test_outputs && rm -f *.txt
	-cd ./test_samples_good && rm -f buckcal_lib.bc
	-cd ./test_samples_bad && rm -f buckcal_lib.bc
